### ISSUE TITLE
Various Social Links Broken

### ISSUE THREAD

**Issue by Justintime50** [nwithan8/nwithan8#1]
It looks like the `LinkedIn` social link is broken as are the links to what I believe is your personal website.

**Comment by nwithan8** [comment]
LinkedIn link fixed in d6b66f7e1d668fb4aca7c233788c76a7e0febe29
Personal website currently inaccessibly due to reverse proxy issue.

**Comment by Justintime50** [comment]
Anything else to do here? Closing out old tickets.

**Comment by nwithan8** [comment]
Website migrated and operating properly again.
